### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by strugee** [NicolasPetton/telepathy.el#1]
This will allow the project to be published on MELPA Stable.

**Comment by NicolasPetton** [comment]
done, thanks!

**Comment by strugee** [comment]
Great!

**Comment by raashidmuhammed** [comment]
I added the following lines in my .emacs file, but no 'telepathy' functions are available during M-x search.
`(add-to-list 'load-path "~/.emacs.d/elpa/telepathy-20131209.458")`
`(require 'telepathy)`

**Comment by strugee** [comment]
@raashidmuhammed don't just comment in random, unrelated GitHub issues asking for help.

That being said, you should be able to just `(require 'telepathy)` without messing with your `load-path` if you properly set up the packaging system. IIRC you need to do something like:

``` elisp
(require 'package)
(package-initialize)
```
